const SUPABASE_URL = "https://tqfocdktvjuwoiyfgesb.supabase.co";
const SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxZm9jZGt0dmp1d29peWZnZXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk5MDg0NTIsImV4cCI6MjEwNTQ4NDQ1Mn0.8TW4fQCQHc4c_xTNBEwOK3lSC9HYCbkTbfXuYQB-S8g";
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON);
const $ = (s) => document.querySelector(s);
let modeJoin = false;
let session = null;
function stampClock(){const d=new Date();const h=d.getHours().toString().padStart(2,"0");const m=d.getMinutes().toString().padStart(2,"0");$("#clock-line").textContent=`Desk time ${h}:${m} · hour ${h}`;}
async function loadFeature(){const {data}=await sb.from("features").select("title,kicker,body,created_at").order("created_at",{ascending:false}).limit(1);const f=data&&data[0];if(!f)return;$("#feat-title").textContent=f.title;$("#feat-kicker").textContent=f.kicker||"";$("#feat-body").textContent=f.body;}
async function loadPublic(){const {data}=await sb.from("posts").select("id,title,body,created_at").eq("is_public",true).order("created_at",{ascending:false}).limit(40);const box=$("#public-list");if(!data||!data.length){box.innerHTML="<p class='hint'>The board is empty. Sign in and mark a note public.</p>";return;}box.innerHTML=data.map(p=>`<article class=\"note\"><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.body)}</p><p class=\"who\">${new Date(p.created_at).toLocaleString()}</p></article>`).join("");}
async function loadMine(){if(!session)return;const {data}=await sb.from("posts").select("id,title,body,is_public,created_at").eq("user_id",session.user.id).order("created_at",{ascending:false});const box=$("#mine-list");if(!data||!data.length){box.innerHTML="<p class='hint'>Nothing in the drawer yet.</p>";return;}box.innerHTML=data.map(p=>`<article class=\"note\"><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.body)}</p><p class=\"who\">${p.is_public?"on the board":"private"} · <button data-toggle=\"${p.id}\" data-pub=\"${p.is_public}\">${p.is_public?"Make private":"Make public"}</button></p></article>`).join("");box.querySelectorAll("[data-toggle]").forEach(btn=>btn.addEventListener("click",async()=>{await sb.from("posts").update({is_public:btn.dataset.pub!=="true"}).eq("id",btn.dataset.toggle);loadMine();loadPublic();}));}
function escapeHtml(s){return String(s||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function setAuthUI(){$("#auth-toggle").textContent=session?"Sign out":"Sign in";$("#desk").classList.toggle("hidden",!session);}
async function refreshAuth(){const {data}=await sb.auth.getSession();session=data.session;setAuthUI();if(session)loadMine();}
document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>document.getElementById(b.dataset.go).scrollIntoView({behavior:"smooth"})));
$("#auth-toggle").addEventListener("click",async()=>{if(session){await sb.auth.signOut();session=null;setAuthUI();return;}$("#auth-modal").classList.remove("hidden");});
$("#close-auth").addEventListener("click",()=>$("#auth-modal").classList.add("hidden"));
$("#flip-auth").addEventListener("click",()=>{modeJoin=!modeJoin;$("#auth-title").textContent=modeJoin?"Join the desk":"Sign in";$("#flip-auth").textContent=modeJoin?"Have an account?":"Need an account?";});
$("#auth-form").addEventListener("submit",async(e)=>{e.preventDefault();const fd=new FormData(e.target);const email=fd.get("email");const password=fd.get("password");const handle=(fd.get("handle")||"").trim();$("#auth-msg").textContent="";try{if(modeJoin){const {error}=await sb.auth.signUp({email,password,options:{data:{handle:handle||email.split("@")[0]}}});if(error)throw error;$("#auth-msg").textContent="Check your email if confirmation is on, then sign in.";}else{const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;$("#auth-modal").classList.add("hidden");}await refreshAuth();}catch(err){$("#auth-msg").textContent=err.message||"Could not continue.";}});
$("#compose").addEventListener("submit",async(e)=>{e.preventDefault();if(!session)return;const fd=new FormData(e.target);const {error}=await sb.from("posts").insert({user_id:session.user.id,title:fd.get("title"),body:fd.get("body"),is_public:fd.get("is_public")==="on"});if(error){alert(error.message);return;}e.target.reset();loadMine();loadPublic();});
sb.auth.onAuthStateChange(()=>refreshAuth());
stampClock();setInterval(stampClock,15000);loadFeature();loadPublic();refreshAuth();setInterval(()=>{loadFeature();loadPublic();},60000);
